{
 "title": "新监控Container_Metrics : OOM-kill/number of container restarts/last exit code",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "CI_SIZE",
    "label": "当前CI量级配置: ",
    "query": "1, 5, 10, 15, 20, 30, 40, 50, 100, 150, 200, 400, 500, 600, 700, 800, 900, 1000, 1200, 1400, 1500, 1600, 2000, 2500, 3000"
   },
   {
    "name": "VAR_T1",
    "label": "查询频度(M): ",
    "query": "1, 5, 6, 7, 8, 9, 10, 12, 15, 20, 30, 40, 50, 60, 80, 100, 120, 150, 200, 240, 300, 360, 420, 480, 540, 600, 720"
   },
   { "name": "VAR_T2", "label": "基线查询 频度(M): ", "query": "1, 5" }
  ]
 },
 "panels": [
  {
   "title": "POD 的 OOM-kill 次数统计",
   "type": "table",
   "gridPos": { "h": 13, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(container_ooms{exported_namespace=\"newmonitor\"}) by (exported_pod)"
    }
   ]
  },
  {
   "title": "POD 的 container_last_exit_code 次数统计",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 0, "y": 13 },
   "targets": [
    {
     "expr": "sum(container_last_exit_code{exported_namespace=\"newmonitor\"}) by (exported_pod)"
    }
   ]
  },
  {
   "title": "POD 的 container_restarts 次数统计",
   "type": "table",
   "gridPos": { "h": 13, "w": 12, "x": 12, "y": 13 },
   "targets": [
    {
     "expr": "sum(container_restarts{exported_namespace=\"newmonitor\"}) by (exported_pod)"
    }
   ]
  }
 ]
}