apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: missing-container-metrics
  namespace: monitoring
  labels:
    k8s-app: missing-container-metrics
    app.kubernetes.io/instance: missing-container-metrics
    app.kubernetes.io/name: missing-container-metrics
    app.kubernetes.io/version: 0.21.0
    app.kubernetes.io/part-of: kube-prometheus
    app: missing-container-metrics
spec:
  selector:
    matchLabels:
      app.kubernetes.io/instance: missing-container-metrics
      app.kubernetes.io/name: missing-container-metrics
      app.kubernetes.io/part-of: kube-prometheus
      k8s-app: missing-container-metrics
      name: missing-container-metrics
      app: missing-container-metrics
  template:
    metadata:
      labels:
        name: missing-container-metrics
        k8s-app: missing-container-metrics
        app.kubernetes.io/instance: missing-container-metrics
        app.kubernetes.io/name: missing-container-metrics
        app.kubernetes.io/version: 0.21.0
        app.kubernetes.io/part-of: kube-prometheus
        app: missing-container-metrics
      annotations:
        prometheus.io/scrape: 'true'
        prometheus.io/port: '3001'
    spec:
      tolerations:
        - key: node-role.kubernetes.io/master
          effect: NoSchedule
      containers:
        - name: missing-container-metrics
          image: dmilhdef/missing-container-metrics:v0.21.0
          imagePullPolicy: IfNotPresent
          env:
            - name: DOCKER
              value: "true"
            - name: CONTAINERD
              value: "false"
          ports:
            - name: http
              containerPort: 3001
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: http
          readinessProbe:
            httpGet:
              path: /metrics
              port: http
          resources:
            limits:
              memory: 20Mi
            requests:
              memory: 20Mi
          volumeMounts:
            - name: dockersock
              mountPath: /var/run/docker.sock
      terminationGracePeriodSeconds: 30
      volumes:
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
